version: '3.9'

services:

  front_app:
    container_name: "dev_movie_app_container"
    build:
      context: .
      dockerfile: "Dockerfile.dev"
    volumes:
      - ".:/application"
      - "/application/node_modules"
    ports:
      - "3000:3000"
